development:
  app: mychoresweb
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-32863580-1"
    MAIL_HOST: "localhost:3000"

production:
  app: mychoresweb
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-32863580-1"
    MAIL_HOST: "mychoresweb.herokuapp.com"
